// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCym2IBPjT9saEWjf2mkyGb11ZSJIP-AOc',
    appId: '1:15349785590:web:116e6670a481ebe1cd9dd7',
    messagingSenderId: '15349785590',
    projectId: 'abcd-7762c',
    authDomain: 'abcd-7762c.firebaseapp.com',
    storageBucket: 'abcd-7762c.firebasestorage.app',
    measurementId: 'G-5EHK09W8GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI20GP_ocAK0N95-yMoeMTX9Ln1_t9Kig',
    appId: '1:15349785590:android:efbbe60c298f6bfdcd9dd7',
    messagingSenderId: '15349785590',
    projectId: 'abcd-7762c',
    storageBucket: 'abcd-7762c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKEpsWeoag3FkW31H5YVBpulLHoFqmvVU',
    appId: '1:15349785590:ios:a84f9b1f492a8869cd9dd7',
    messagingSenderId: '15349785590',
    projectId: 'abcd-7762c',
    storageBucket: 'abcd-7762c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKEpsWeoag3FkW31H5YVBpulLHoFqmvVU',
    appId: '1:15349785590:ios:a84f9b1f492a8869cd9dd7',
    messagingSenderId: '15349785590',
    projectId: 'abcd-7762c',
    storageBucket: 'abcd-7762c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCym2IBPjT9saEWjf2mkyGb11ZSJIP-AOc',
    appId: '1:15349785590:web:31d00b7a03d98df5cd9dd7',
    messagingSenderId: '15349785590',
    projectId: 'abcd-7762c',
    authDomain: 'abcd-7762c.firebaseapp.com',
    storageBucket: 'abcd-7762c.firebasestorage.app',
    measurementId: 'G-GWLLFWE62Q',
  );

}