import 'dart:io';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:image_picker/image_picker.dart';
import 'package:uuid/uuid.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'artwork_detail_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Digital Art Gallery',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const GalleryScreen(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class GalleryScreen extends StatefulWidget {
  const GalleryScreen({super.key});

  @override
  State<GalleryScreen> createState() => _GalleryScreenState();
}

class _GalleryScreenState extends State<GalleryScreen> {
  Future<void> _deleteArtwork(String id) async {
    await _firestore.collection("artworks").doc(id).delete();
    if (!mounted) return;
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(const SnackBar(content: Text("Artwork deleted!")));
  }

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final ImagePicker _picker = ImagePicker();

  Future<void> _addArtwork() async {
    final picked = await _picker.pickImage(source: ImageSource.gallery);
    if (!mounted) return;
    if (picked == null) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text("No image selected")));
      return;
    }

    String artistName = "";
    String description = "";
    String title = "";

    await showDialog(
      context: context,
      builder: (context) {
        final artistController = TextEditingController();
        final descController = TextEditingController();
        final titleController = TextEditingController();
        return AlertDialog(
          title: const Text("Artwork Details"),
          content: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                TextField(
                  controller: titleController,
                  decoration: const InputDecoration(labelText: "Title"),
                ),
                TextField(
                  controller: artistController,
                  decoration: const InputDecoration(labelText: "Artist Name"),
                ),
                TextField(
                  controller: descController,
                  decoration: const InputDecoration(labelText: "Description"),
                  maxLines: 2,
                ),
              ],
            ),
          ),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.of(context).pop();
              },
              child: const Text("Cancel"),
            ),
            ElevatedButton(
              onPressed: () {
                artistName = artistController.text.trim();
                description = descController.text.trim();
                title = titleController.text.trim();
                Navigator.of(context).pop();
              },
              child: const Text("Save"),
            ),
          ],
        );
      },
    );

    if (!mounted) return;
    if (artistName.isEmpty && description.isEmpty && title.isEmpty) {
      // User cancelled
      return;
    }

    final id = const Uuid().v4();
    await _firestore.collection("artworks").doc(id).set({
      "id": id,
      "imageUrl": picked.path, // storing local path for now
      "title": title.isNotEmpty ? title : "My Artwork",
      "artistName": artistName.isNotEmpty ? artistName : "Unknown Artist",
      "description": description,
      "createdAt": FieldValue.serverTimestamp(),
    });

    if (!mounted) return;
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(const SnackBar(content: Text("Artwork added!")));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        title: const Text(
          "Digital Art Gallery",
          textAlign: TextAlign.center,
          style: TextStyle(
            color: Colors.black, // semi-transparent white
            shadows: [
              Shadow(
                blurRadius: 8,
                color: Colors.black54,
                offset: Offset(3, 3),
              ),
            ],
            fontFamily: 'Courier New',
            fontWeight: FontWeight.bold,
            fontSize: 24,
          ),
        ),
        centerTitle: true,

        elevation: 0,
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: Colors.white.withValues(alpha: 0.7),
        onPressed: _addArtwork,
        child: const Icon(Icons.add),
      ),
      body: Stack(
        fit: StackFit.expand,
        children: [
          Positioned.fill(
            child: Image.asset('assets/theme1.jpg', fit: BoxFit.cover),
          ),

          StreamBuilder<QuerySnapshot>(
            stream:
                _firestore
                    .collection("artworks")
                    .orderBy("createdAt", descending: true)
                    .snapshots(),
            builder: (context, snapshot) {
              if (snapshot.hasError) {
                return const Center(child: Text("Error loading artworks"));
              }
              if (snapshot.connectionState == ConnectionState.waiting) {
                return const Center(child: CircularProgressIndicator());
              }

              final docs = snapshot.data?.docs ?? [];

              if (docs.isEmpty) {
                return const Center(child: Text("No artworks yet"));
              }

              return ListView.builder(
                itemCount: docs.length,
                itemBuilder: (context, index) {
                  final data = docs[index].data() as Map<String, dynamic>;
                  final title = data["title"] ?? "Untitled";
                  final artist = data["artistName"] ?? "Anonymous";
                  final description = data["description"] ?? "";
                  final imagePath = data["imageUrl"];
                  final id = data["id"];

                  return Card(
                    color: Colors.white.withValues(alpha: 0.7),
                    child: ListTile(
                      leading:
                          imagePath != null
                              ? Image.file(
                                File(imagePath),
                                width: 60,
                                height: 60,
                                fit: BoxFit.cover,
                              )
                              : const Icon(Icons.image),
                      title: Text(title),
                      subtitle: Text("by $artist"),
                      trailing: IconButton(
                        icon: const Icon(Icons.delete, color: Colors.red),
                        onPressed: () async {
                          final confirm = await showDialog<bool>(
                            context: context,
                            builder:
                                (context) => AlertDialog(
                                  title: const Text("Delete Artwork"),
                                  content: const Text(
                                    "Are you sure you want to delete this artwork?",
                                  ),
                                  actions: [
                                    TextButton(
                                      onPressed:
                                          () =>
                                              Navigator.of(context).pop(false),
                                      child: const Text("Cancel"),
                                    ),
                                    TextButton(
                                      onPressed:
                                          () => Navigator.of(context).pop(true),
                                      child: const Text(
                                        "Delete",
                                        style: TextStyle(color: Colors.red),
                                      ),
                                    ),
                                  ],
                                ),
                          );
                          if (confirm == true) {
                            _deleteArtwork(id);
                          }
                        },
                      ),
                      onTap: () {
                        Navigator.of(context).push(
                          MaterialPageRoute(
                            builder:
                                (_) => ArtworkDetailPage(
                                  title: title,
                                  artist: artist,
                                  description: description,
                                  imagePath: imagePath,
                                ),
                          ),
                        );
                      },
                    ),
                  );
                },
              );
            },
          ),
        ],
      ),
    );
  }
}
